# Dockerfile для разработки
FROM node:22-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем все файлы проекта
COPY . .

# Открываем порт для Vite
EXPOSE 5173

# Запускаем сервер разработки в режиме --host для доступа извне контейнера
CMD ["npm", "run", "dev"] 