services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bs-budget-tracker
    ports:
      - "8005:80"
    restart: unless-stopped
    
  # Сервис для разработки с горячей перезагрузкой
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bs-budget-tracker-dev
    ports:
      - "5173:5173"  # порт Vite для разработки
    volumes:
      - ./:/app  # монтирование текущей директории в контейнер
      - /app/node_modules  # исключение node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev 